// The web detector's verdicts over the synthetic streams that the Android unit
// test replays (scripts/export-motion-golden.mjs). Guards the behaviour itself
// and that the committed golden file is current.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { VARIANTS, runWebDetector } from '../scripts/export-motion-golden.mjs';

const golden = readFileSync(new URL('../android/app/src/test/resources/motion-golden.txt', import.meta.url), 'utf8');

test('pull and 토독 alarm; wind, knocks and dropouts do not; a new rest angle is adopted', () => {
  for (const v of VARIANTS) {
    const lines = runWebDetector(v);
    const ticks = lines.filter((l) => l.startsWith('T ')).map((l) => l.split(' '));
    const alarms = ticks.filter((p) => p[5] === '1').map((p) => ({ t: Number(p[1]), pattern: p[3] }));
    const label = `${v.hz} Hz${v.gravityOnly ? ' gravity-only' : ''}`;
    assert.deepEqual(alarms.map((a) => a.pattern), ['strong_pull', 'tap'], label);
    assert.ok(alarms[0].t > 9000 && alarms[0].t < 10000, `${label} pull at ${alarms[0].t}`);
    assert.ok(alarms[1].t > 19000 && alarms[1].t < 20000, `${label} tap at ${alarms[1].t}`);
    const stateAt = (t) => ticks.find((p) => Number(p[1]) >= t)[6];
    assert.equal(stateAt(36300), 'stabilizing', `${label} knock`);
    assert.equal(stateAt(43800), 'error', `${label} dropout`);
    assert.equal(stateAt(46000), 'armed', `${label} recovers`);
    // Knocked at 47 s and left at a 20° angle: re-stabilising, then watching again.
    assert.equal(stateAt(47400), 'stabilizing', `${label} second knock`);
    assert.equal(stateAt(51000), 'stabilizing', `${label} still settling`);
    assert.equal(stateAt(57000), 'armed', `${label} watching at the new angle`);
    assert.equal(stateAt(59900), 'armed', `${label} stays armed`);
  }
});

test('the golden file for the Android test is up to date', () => {
  const expected = ['# generated by scripts/export-motion-golden.mjs — do not edit'];
  for (const v of VARIANTS) {
    expected.push(`V ${v.hz} ${v.gravityOnly ? 1 : 0}`);
    expected.push(...runWebDetector(v));
  }
  assert.equal(golden, `${expected.join('\n')}\n`, 'run: node scripts/export-motion-golden.mjs');
});
